dist: trusty
sudo: true
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
before_install:
  - ./travis.sh
install:
  - pip install -r requirements-dev.txt
  - make cython
  - pip install .
script:
  - make test
